/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhyUsRouteImport } from './routes/why-us'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as OurWorkRouteImport } from './routes/our-work'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceAreasIndexRouteImport } from './routes/service-areas/index'
import { Route as ServicesWarehouseFloorStripingRouteImport } from './routes/services/warehouse-floor-striping'
import { Route as ServicesPrecisionLineworkSignageRouteImport } from './routes/services/precision-linework-signage'
import { Route as ServicesParkingLotStripingRouteImport } from './routes/services/parking-lot-striping'
import { Route as ServicesLayoutDesignRouteImport } from './routes/services/layout-design'
import { Route as ServicesAsphaltSealcoatingRouteImport } from './routes/services/asphalt-sealcoating'
import { Route as ServiceAreasSlugRouteImport } from './routes/service-areas/$slug'

const WhyUsRoute = WhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/why-us.lazy').then((d) => d.Route))
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const OurWorkRoute = OurWorkRouteImport.update({
  id: '/our-work',
  path: '/our-work',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/our-work.lazy').then((d) => d.Route))
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/faq.lazy').then((d) => d.Route))
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const ServiceAreasIndexRoute = ServiceAreasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiceAreasRoute,
} as any).lazy(() =>
  import('./routes/service-areas/index.lazy').then((d) => d.Route),
)
const ServicesWarehouseFloorStripingRoute =
  ServicesWarehouseFloorStripingRouteImport.update({
    id: '/services/warehouse-floor-striping',
    path: '/services/warehouse-floor-striping',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/services/warehouse-floor-striping.lazy').then(
      (d) => d.Route,
    ),
  )
const ServicesPrecisionLineworkSignageRoute =
  ServicesPrecisionLineworkSignageRouteImport.update({
    id: '/services/precision-linework-signage',
    path: '/services/precision-linework-signage',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/services/precision-linework-signage.lazy').then(
      (d) => d.Route,
    ),
  )
const ServicesParkingLotStripingRoute =
  ServicesParkingLotStripingRouteImport.update({
    id: '/services/parking-lot-striping',
    path: '/services/parking-lot-striping',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/services/parking-lot-striping.lazy').then((d) => d.Route),
  )
const ServicesLayoutDesignRoute = ServicesLayoutDesignRouteImport.update({
  id: '/services/layout-design',
  path: '/services/layout-design',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/services/layout-design.lazy').then((d) => d.Route),
)
const ServicesAsphaltSealcoatingRoute =
  ServicesAsphaltSealcoatingRouteImport.update({
    id: '/services/asphalt-sealcoating',
    path: '/services/asphalt-sealcoating',
    getParentRoute: () => rootRouteImport,
  } as any).lazy(() =>
    import('./routes/services/asphalt-sealcoating.lazy').then((d) => d.Route),
  )
const ServiceAreasSlugRoute = ServiceAreasSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServiceAreasRoute,
} as any).lazy(() =>
  import('./routes/service-areas/$slug.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/our-work': typeof OurWorkRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/service-areas': typeof ServiceAreasRouteWithChildren
  '/terms-of-service': typeof TermsOfServiceRoute
  '/why-us': typeof WhyUsRoute
  '/service-areas/$slug': typeof ServiceAreasSlugRoute
  '/services/asphalt-sealcoating': typeof ServicesAsphaltSealcoatingRoute
  '/services/layout-design': typeof ServicesLayoutDesignRoute
  '/services/parking-lot-striping': typeof ServicesParkingLotStripingRoute
  '/services/precision-linework-signage': typeof ServicesPrecisionLineworkSignageRoute
  '/services/warehouse-floor-striping': typeof ServicesWarehouseFloorStripingRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/our-work': typeof OurWorkRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/why-us': typeof WhyUsRoute
  '/service-areas/$slug': typeof ServiceAreasSlugRoute
  '/services/asphalt-sealcoating': typeof ServicesAsphaltSealcoatingRoute
  '/services/layout-design': typeof ServicesLayoutDesignRoute
  '/services/parking-lot-striping': typeof ServicesParkingLotStripingRoute
  '/services/precision-linework-signage': typeof ServicesPrecisionLineworkSignageRoute
  '/services/warehouse-floor-striping': typeof ServicesWarehouseFloorStripingRoute
  '/service-areas': typeof ServiceAreasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/our-work': typeof OurWorkRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/service-areas': typeof ServiceAreasRouteWithChildren
  '/terms-of-service': typeof TermsOfServiceRoute
  '/why-us': typeof WhyUsRoute
  '/service-areas/$slug': typeof ServiceAreasSlugRoute
  '/services/asphalt-sealcoating': typeof ServicesAsphaltSealcoatingRoute
  '/services/layout-design': typeof ServicesLayoutDesignRoute
  '/services/parking-lot-striping': typeof ServicesParkingLotStripingRoute
  '/services/precision-linework-signage': typeof ServicesPrecisionLineworkSignageRoute
  '/services/warehouse-floor-striping': typeof ServicesWarehouseFloorStripingRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/faq'
    | '/our-work'
    | '/privacy-policy'
    | '/service-areas'
    | '/terms-of-service'
    | '/why-us'
    | '/service-areas/$slug'
    | '/services/asphalt-sealcoating'
    | '/services/layout-design'
    | '/services/parking-lot-striping'
    | '/services/precision-linework-signage'
    | '/services/warehouse-floor-striping'
    | '/service-areas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faq'
    | '/our-work'
    | '/privacy-policy'
    | '/terms-of-service'
    | '/why-us'
    | '/service-areas/$slug'
    | '/services/asphalt-sealcoating'
    | '/services/layout-design'
    | '/services/parking-lot-striping'
    | '/services/precision-linework-signage'
    | '/services/warehouse-floor-striping'
    | '/service-areas'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/faq'
    | '/our-work'
    | '/privacy-policy'
    | '/service-areas'
    | '/terms-of-service'
    | '/why-us'
    | '/service-areas/$slug'
    | '/services/asphalt-sealcoating'
    | '/services/layout-design'
    | '/services/parking-lot-striping'
    | '/services/precision-linework-signage'
    | '/services/warehouse-floor-striping'
    | '/service-areas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  OurWorkRoute: typeof OurWorkRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ServiceAreasRoute: typeof ServiceAreasRouteWithChildren
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  WhyUsRoute: typeof WhyUsRoute
  ServicesAsphaltSealcoatingRoute: typeof ServicesAsphaltSealcoatingRoute
  ServicesLayoutDesignRoute: typeof ServicesLayoutDesignRoute
  ServicesParkingLotStripingRoute: typeof ServicesParkingLotStripingRoute
  ServicesPrecisionLineworkSignageRoute: typeof ServicesPrecisionLineworkSignageRoute
  ServicesWarehouseFloorStripingRoute: typeof ServicesWarehouseFloorStripingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/why-us': {
      id: '/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof WhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-work': {
      id: '/our-work'
      path: '/our-work'
      fullPath: '/our-work'
      preLoaderRoute: typeof OurWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/': {
      id: '/service-areas/'
      path: '/'
      fullPath: '/service-areas/'
      preLoaderRoute: typeof ServiceAreasIndexRouteImport
      parentRoute: typeof ServiceAreasRoute
    }
    '/services/warehouse-floor-striping': {
      id: '/services/warehouse-floor-striping'
      path: '/services/warehouse-floor-striping'
      fullPath: '/services/warehouse-floor-striping'
      preLoaderRoute: typeof ServicesWarehouseFloorStripingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/precision-linework-signage': {
      id: '/services/precision-linework-signage'
      path: '/services/precision-linework-signage'
      fullPath: '/services/precision-linework-signage'
      preLoaderRoute: typeof ServicesPrecisionLineworkSignageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/parking-lot-striping': {
      id: '/services/parking-lot-striping'
      path: '/services/parking-lot-striping'
      fullPath: '/services/parking-lot-striping'
      preLoaderRoute: typeof ServicesParkingLotStripingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/layout-design': {
      id: '/services/layout-design'
      path: '/services/layout-design'
      fullPath: '/services/layout-design'
      preLoaderRoute: typeof ServicesLayoutDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/asphalt-sealcoating': {
      id: '/services/asphalt-sealcoating'
      path: '/services/asphalt-sealcoating'
      fullPath: '/services/asphalt-sealcoating'
      preLoaderRoute: typeof ServicesAsphaltSealcoatingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/$slug': {
      id: '/service-areas/$slug'
      path: '/$slug'
      fullPath: '/service-areas/$slug'
      preLoaderRoute: typeof ServiceAreasSlugRouteImport
      parentRoute: typeof ServiceAreasRoute
    }
  }
}

interface ServiceAreasRouteChildren {
  ServiceAreasSlugRoute: typeof ServiceAreasSlugRoute
  ServiceAreasIndexRoute: typeof ServiceAreasIndexRoute
}

const ServiceAreasRouteChildren: ServiceAreasRouteChildren = {
  ServiceAreasSlugRoute: ServiceAreasSlugRoute,
  ServiceAreasIndexRoute: ServiceAreasIndexRoute,
}

const ServiceAreasRouteWithChildren = ServiceAreasRoute._addFileChildren(
  ServiceAreasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  OurWorkRoute: OurWorkRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ServiceAreasRoute: ServiceAreasRouteWithChildren,
  TermsOfServiceRoute: TermsOfServiceRoute,
  WhyUsRoute: WhyUsRoute,
  ServicesAsphaltSealcoatingRoute: ServicesAsphaltSealcoatingRoute,
  ServicesLayoutDesignRoute: ServicesLayoutDesignRoute,
  ServicesParkingLotStripingRoute: ServicesParkingLotStripingRoute,
  ServicesPrecisionLineworkSignageRoute: ServicesPrecisionLineworkSignageRoute,
  ServicesWarehouseFloorStripingRoute: ServicesWarehouseFloorStripingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
